// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as FormStyles$App from "./FormStyles.bs.js";

function Buttons(Props) {
  var valid = Props.valid;
  var reset = Props.reset;
  return React.createElement("div", {
              className: "field is-grouped is-pulled-right"
            }, React.createElement("div", {
                  className: FormStyles$App.buttonStyle
                }, React.createElement("button", {
                      className: "button is-link is-danger is-light",
                      onClick: (function (param) {
                          return Curry._1(reset, /* () */0);
                        })
                    }, "Cancel")), React.createElement("div", {
                  className: FormStyles$App.buttonStyle
                }, React.createElement("button", {
                      className: "button is-link is-warning is-light",
                      disabled: !valid
                    }, React.createElement("span", undefined, "Save"))));
}

var make = Buttons;

var $$default = Buttons;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
