// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

function getFieldStateStyle(fieldState) {
  if (fieldState !== undefined) {
    var match = fieldState;
    if (match.tag) {
      return "is-danger";
    } else if (match[0]) {
      return "";
    } else {
      return "is-success";
    }
  } else {
    return "";
  }
}

function inputFieldStyles(fieldState) {
  return Css.merge(/* :: */[
              "input",
              /* :: */[
                getFieldStateStyle(fieldState),
                /* [] */0
              ]
            ]);
}

var checkboxStyle = getFieldStateStyle;

function textareaFieldStyles(fieldState) {
  return Css.merge(/* :: */[
              "textarea",
              /* :: */[
                getFieldStateStyle(fieldState),
                /* [] */0
              ]
            ]);
}

function selectFieldStyles(fieldState) {
  return Css.merge(/* :: */[
              "field",
              /* :: */[
                getFieldStateStyle(fieldState),
                /* [] */0
              ]
            ]);
}

var sectionTitleStyles = Css.merge(/* :: */[
      "title",
      /* :: */[
        Css.style(/* :: */[
              Css.color(Css.rgb(232, 95, 88)),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var labelStyle = Css.merge(/* :: */[
      "label",
      /* :: */[
        Css.style(/* :: */[
              Css.width(Css.px(150)),
              /* :: */[
                Css.textAlign(/* left */-944764921),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var buttonStyle = Css.merge(/* :: */[
      "field",
      /* :: */[
        Css.style(/* :: */[
              Css.marginTop(Css.px(10)),
              /* :: */[
                Css.marginRight(Css.px(10)),
                /* :: */[
                  Css.textAlign(/* center */98248149),
                  /* [] */0
                ]
              ]
            ]),
        /* [] */0
      ]
    ]);

export {
  getFieldStateStyle ,
  inputFieldStyles ,
  checkboxStyle ,
  textareaFieldStyles ,
  selectFieldStyles ,
  sectionTitleStyles ,
  labelStyle ,
  buttonStyle ,
  
}
/* sectionTitleStyles Not a pure module */
