// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyles$App from "./FormStyles.bs.js";

function HorizontalInputField(Props) {
  var inputId = Props.inputId;
  var value = Props.value;
  var onChange = Props.onChange;
  var onBlur = Props.onBlur;
  var result = Props.result;
  var label = Props.label;
  var match = Props.placeholder;
  var placeholder = match !== undefined ? match : "";
  var match$1 = Props.type_;
  var type_ = match$1 !== undefined ? match$1 : "text";
  var match$2 = type_ === "checkbox";
  var classNames = match$2 ? FormStyles$App.checkboxStyle(result) : FormStyles$App.inputFieldStyles(result);
  var tmp;
  if (result !== undefined) {
    var match$3 = result;
    tmp = match$3.tag ? React.createElement("div", {
            className: "help is-danger",
            name: "errormessage"
          }, match$3[0]) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "field is-horizontal"
            }, React.createElement("div", {
                  className: "field-label is-normal"
                }, React.createElement("label", {
                      className: FormStyles$App.labelStyle
                    }, label)), React.createElement("div", {
                  className: "field-body"
                }, React.createElement("div", {
                      className: "field"
                    }, React.createElement("input", {
                          className: classNames,
                          id: inputId,
                          placeholder: placeholder,
                          type: type_,
                          value: value,
                          onBlur: onBlur,
                          onChange: onChange
                        }))), tmp);
}

var make = HorizontalInputField;

var $$default = HorizontalInputField;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
