// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyles$App from "./FormStyles.bs.js";

function InputField(Props) {
  var inputId = Props.inputId;
  var value = Props.value;
  var onChange = Props.onChange;
  var onBlur = Props.onBlur;
  var result = Props.result;
  var label = Props.label;
  var match = Props.placeholder;
  var placeholder = match !== undefined ? match : "";
  var match$1 = Props.type_;
  var type_ = match$1 !== undefined ? match$1 : "text";
  var match$2 = Props.isVertical;
  var isVertical = match$2 !== undefined ? match$2 : true;
  var match$3 = type_ === "checkbox";
  var classNames = match$3 ? FormStyles$App.checkboxStyle(result) : FormStyles$App.inputFieldStyles(result);
  if (isVertical) {
    var tmp;
    if (result !== undefined) {
      var match$4 = result;
      tmp = match$4.tag ? React.createElement("div", {
              className: "help is-danger",
              name: "errormessage"
            }, match$4[0]) : null;
    } else {
      tmp = null;
    }
    return React.createElement("div", {
                className: "field "
              }, React.createElement("label", {
                    className: "label"
                  }, label), React.createElement("div", {
                    className: "field-body"
                  }, React.createElement("div", {
                        className: "field"
                      }, React.createElement("input", {
                            className: classNames,
                            id: inputId,
                            placeholder: placeholder,
                            type: type_,
                            value: value,
                            onBlur: onBlur,
                            onChange: onChange
                          }))), tmp);
  } else {
    var tmp$1;
    if (result !== undefined) {
      var match$5 = result;
      tmp$1 = match$5.tag ? React.createElement("div", {
              className: "help is-danger",
              name: "errormessage"
            }, match$5[0]) : null;
    } else {
      tmp$1 = null;
    }
    return React.createElement("div", {
                className: "field is-horizontal"
              }, React.createElement("div", {
                    className: "field-label is-normal"
                  }, React.createElement("label", {
                        className: "label"
                      }, label)), React.createElement("div", {
                    className: "field-body"
                  }, React.createElement("div", {
                        className: "field"
                      }, React.createElement("input", {
                            className: classNames,
                            id: inputId,
                            placeholder: placeholder,
                            type: type_,
                            value: value,
                            onBlur: onBlur,
                            onChange: onChange
                          }))), tmp$1);
  }
}

var make = InputField;

var $$default = InputField;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
