// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyles$App from "./FormStyles.bs.js";

function SectionTitle(Props) {
  var title = Props.title;
  return React.createElement("div", {
              className: FormStyles$App.sectionTitleStyles
            }, React.createElement("p", {
                  className: FormStyles$App.sectionTitleStyles
                }, title));
}

var make = SectionTitle;

var $$default = SectionTitle;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
