// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyles$App from "./FormStyles.bs.js";

function TextAreaField(Props) {
  var inputId = Props.inputId;
  var value = Props.value;
  var onChange = Props.onChange;
  var onBlur = Props.onBlur;
  var result = Props.result;
  var placeholder = Props.placeholder;
  var label = Props.label;
  var tmp;
  if (result !== undefined) {
    var match = result;
    tmp = match.tag ? React.createElement("div", {
            className: "help is-danger"
          }, match[0]) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "field"
            }, React.createElement("label", {
                  className: "label"
                }, label), React.createElement("div", {
                  className: "field-body"
                }, React.createElement("div", {
                      className: "field"
                    }, React.createElement("div", {
                          className: "control"
                        }, React.createElement("textarea", {
                              className: FormStyles$App.textareaFieldStyles(result),
                              id: inputId,
                              placeholder: placeholder,
                              type: "text",
                              value: value,
                              onBlur: onBlur,
                              onChange: onChange
                            })))), tmp);
}

var make = TextAreaField;

var $$default = TextAreaField;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
