// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var containerStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.marginLeft(Css.px(10)),
            /* :: */[
              Css.marginRight(Css.px(10)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "container",
        /* [] */0
      ]
    ]);

var submitLevelStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.background(Css.rgb(41, 12, 171)),
            /* :: */[
              Css.marginTop(Css.px(5)),
              /* :: */[
                Css.color(Css.rgb(249, 251, 249)),
                /* [] */0
              ]
            ]
          ]),
      /* :: */[
        "level",
        /* [] */0
      ]
    ]);

var titleStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.marginLeft(Css.px(20)),
            /* :: */[
              Css.color(Css.rgb(255, 255, 255)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "title",
        /* [] */0
      ]
    ]);

export {
  containerStyles ,
  submitLevelStyles ,
  titleStyles ,
  
}
/* containerStyles Not a pure module */
