// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactSelect from "react-select";
import * as FormStyles$App from "../../base/form/input/FormStyles.bs.js";

var titles = /* array */[
  {
    label: "None",
    value: ""
  },
  {
    label: "Mr",
    value: "Mr"
  },
  {
    label: "Mrs",
    value: "Mrs"
  },
  {
    label: "Miss",
    value: "Miss"
  }
];

function FirstNameInput(Props) {
  var firstNamevalue = Props.firstNamevalue;
  var titleValue = Props.titleValue;
  var onTitleChange = Props.onTitleChange;
  var onFirstNameChange = Props.onFirstNameChange;
  var onBlur = Props.onBlur;
  var titleResult = Props.titleResult;
  var firstNameResult = Props.firstNameResult;
  var match = Props.placeholder;
  var placeholder = match !== undefined ? match : "John";
  var match$1 = Props.type_;
  var type_ = match$1 !== undefined ? match$1 : "text";
  var tmp;
  if (firstNameResult !== undefined) {
    var match$2 = firstNameResult;
    tmp = match$2.tag ? React.createElement("div", {
            className: "help is-danger",
            name: "errormessage"
          }, match$2[0]) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "field "
            }, React.createElement("label", {
                  className: "label"
                }, "First Name"), React.createElement("div", {
                  className: "field-body is-grouped"
                }, React.createElement("div", {
                      className: FormStyles$App.selectFieldStyles(titleResult)
                    }, React.createElement(ReactSelect.default, {
                          options: titles,
                          placeholder: "None",
                          value: titleValue,
                          instanceId: "title",
                          onChange: onTitleChange
                        })), React.createElement("div", {
                      className: "field"
                    }, React.createElement("input", {
                          className: FormStyles$App.inputFieldStyles(firstNameResult),
                          id: "firstName",
                          placeholder: placeholder,
                          type: type_,
                          value: firstNamevalue,
                          onBlur: onBlur,
                          onChange: onFirstNameChange
                        }), tmp)));
}

var make = FirstNameInput;

var $$default = FirstNameInput;

export {
  titles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
