// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactSelect from "react-select";
import * as FormStyles$App from "../../base/form/input/FormStyles.bs.js";

var states = /* array */[
  {
    label: "New South Wales",
    value: "NSW"
  },
  {
    label: "Victoria",
    value: "VIC"
  },
  {
    label: "Queensland",
    value: "QLD"
  },
  {
    label: "Western Australia",
    value: "WA"
  },
  {
    label: "South Australi",
    value: "SA"
  },
  {
    label: "Tasmania",
    value: "TAS"
  }
];

function StateInput(Props) {
  var config = Props.config;
  var value = Props.value;
  var result = Props.result;
  var onChange = Props.onChange;
  var tmp;
  if (result !== undefined) {
    var match = result;
    tmp = match.tag ? React.createElement("div", {
            className: "help is-danger",
            name: "errormessage"
          }, match[0]) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "column"
            }, React.createElement("div", {
                  className: "field "
                }, React.createElement("label", {
                      className: "label"
                    }, config.label), React.createElement("div", {
                      className: "field-body "
                    }, React.createElement("div", {
                          className: FormStyles$App.selectFieldStyles(result)
                        }, React.createElement(ReactSelect.default, {
                              options: states,
                              placeholder: config.placeholder,
                              value: value,
                              instanceId: config.inputId,
                              onChange: onChange
                            }))), tmp));
}

var make = StateInput;

var $$default = StateInput;

export {
  states ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
