// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FooterStyles$App from "./FooterStyles.bs.js";
import * as FooterContent$App from "./FooterContent.bs.js";

function str(prim) {
  return prim;
}

function Footer(Props) {
  return React.createElement("footer", {
              className: FooterStyles$App.footerStyles
            }, React.createElement("div", {
                  className: FooterStyles$App.footerColumnsStyles
                }, React.createElement(FooterContent$App.make, {
                      content: "@Crunch Accounting All right reserved"
                    }), React.createElement(FooterContent$App.make, {
                      content: "Privacy Policy"
                    }), React.createElement(FooterContent$App.make, {
                      content: "Terms of Service"
                    })));
}

var make = Footer;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
