// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FooterStyles$App from "./FooterStyles.bs.js";

function str(prim) {
  return prim;
}

function FooterContent(Props) {
  var content = Props.content;
  return React.createElement("div", {
              className: FooterStyles$App.footerColumnStyles
            }, React.createElement("a", undefined, content));
}

var make = FooterContent;

var $$default = FooterContent;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
