// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var footerStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.background(Css.rgb(244, 244, 244)),
            /* :: */[
              Css.height(Css.px(30)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "footer",
        /* [] */0
      ]
    ]);

var footerColumnsStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.textAlign(/* center */98248149),
            /* [] */0
          ]),
      /* :: */[
        "columns",
        /* [] */0
      ]
    ]);

var footerColumnStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.color(Css.rgb(150, 142, 117)),
            /* :: */[
              Css.fontSize(Css.px(12)),
              /* :: */[
                Css.marginBottom(Css.px(10)),
                /* [] */0
              ]
            ]
          ]),
      /* :: */[
        "column",
        /* [] */0
      ]
    ]);

export {
  footerStyles ,
  footerColumnsStyles ,
  footerColumnStyles ,
  
}
/* footerStyles Not a pure module */
