// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NavbarStyles$App from "./NavbarStyles.bs.js";

function Navbar(Props) {
  return React.createElement("nav", {
              className: "nav",
              id: "topnav"
            }, React.createElement("a", {
                  className: NavbarStyles$App.logoStyles
                }, React.createElement("img", {
                      src: "../../../static/images/logo.png"
                    })));
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
