// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var linkStyle = Css.selector("a", /* :: */[
      Css.color(Css.rgb(242, 242, 242)),
      /* [] */0
    ]);

var linkHover = Css.selector("a:hover", /* :: */[
      Css.borderBottom(Css.px(1), Css.solid, Css.white),
      /* [] */0
    ]);

var subtitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.color(Css.rgba(255, 255, 255, 0.7)),
            /* :: */[
              Css.fontWeight(Css.bold),
              /* :: */[
                Css.marginTop(Css.px(13)),
                /* :: */[
                  Css.marginLeft(Css.px(10)),
                  /* :: */[
                    Css.important(Css.marginBottom(Css.px(0))),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "subtitle",
        /* [] */0
      ]
    ]);

var navbarBrand = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontFamily("Open Sans, Helvetica Neue, Arial, sans-serif"),
            /* [] */0
          ]),
      /* :: */[
        "navbar-brand",
        /* [] */0
      ]
    ]);

var topnavStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.background(Css.rgb(0, 107, 198)),
            /* [] */0
          ]),
      /* :: */[
        "navbar",
        /* :: */[
          "main-title",
          /* [] */0
        ]
      ]
    ]);

var logoStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.flexDirection(Css.column),
            /* :: */[
              Css.justifyContent(Css.center),
              /* :: */[
                Css.textAlign(Css.center),
                /* [] */0
              ]
            ]
          ]),
      /* :: */[
        "navbar-item",
        /* [] */0
      ]
    ]);

export {
  linkStyle ,
  linkHover ,
  subtitle ,
  navbarBrand ,
  topnavStyles ,
  logoStyles ,
  
}
/* linkStyle Not a pure module */
