// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SingleInputContainer$App from "./SingleInputContainer.bs.js";

function RowContainer(Props) {
  var config1 = Props.config1;
  var value1 = Props.value1;
  var onBlur1 = Props.onBlur1;
  var result1 = Props.result1;
  var onChange1 = Props.onChange1;
  var config2 = Props.config2;
  var value2 = Props.value2;
  var onBlur2 = Props.onBlur2;
  var result2 = Props.result2;
  var onChange2 = Props.onChange2;
  var match = Props.isHorizontal;
  var isHorizontal = match !== undefined ? match : false;
  return React.createElement("div", {
              className: "columns"
            }, React.createElement(SingleInputContainer$App.make, {
                  config: config1,
                  value: value1,
                  onBlur: onBlur1,
                  result: result1,
                  onChange: onChange1,
                  isHorizontal: isHorizontal
                }), React.createElement(SingleInputContainer$App.make, {
                  config: config2,
                  value: value2,
                  onBlur: onBlur2,
                  result: result2,
                  onChange: onChange2,
                  isHorizontal: isHorizontal
                }));
}

var make = RowContainer;

export {
  make ,
  
}
/* react Not a pure module */
