// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ContactForm$App from "../src/components/contact/form/ContactForm.bs.js";

function CreateContact(Props) {
  return React.createElement(ContactForm$App.make, { });
}

var make = CreateContact;

var $$default = CreateContact;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
