// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CreateContact$App from "./createContact.bs.js";

function str(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement("div", undefined, React.createElement(CreateContact$App.make, { }));
}

var make = Index;

var $$default = Index;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
