// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ContactModalText$App from "./ContactModalText.bs.js";
import * as ContactModalStyles$App from "./ContactModalStyles.bs.js";

function ContactModalRow(Props) {
  var field1 = Props.field1;
  var value1 = Props.value1;
  var match = Props.field2;
  var field2 = match !== undefined ? match : "";
  var match$1 = Props.value2;
  var value2 = match$1 !== undefined ? match$1 : "";
  return React.createElement("div", {
              className: "columns "
            }, React.createElement(ContactModalText$App.make, {
                  text: field1,
                  className: ContactModalStyles$App.labelStyles
                }), React.createElement(ContactModalText$App.make, {
                  text: value1,
                  className: ContactModalStyles$App.valueStyles
                }), React.createElement(ContactModalText$App.make, {
                  text: field2,
                  className: ContactModalStyles$App.labelStyles
                }), React.createElement(ContactModalText$App.make, {
                  text: value2,
                  className: ContactModalStyles$App.valueStyles
                }));
}

var make = ContactModalRow;

var $$default = ContactModalRow;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
