// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function ContactModalText(Props) {
  var text = Props.text;
  var className = Props.className;
  return React.createElement("div", {
              className: className
            }, text);
}

var make = ContactModalText;

var $$default = ContactModalText;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
