// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var modalHeaderStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.backgroundColor(Css.white),
            /* :: */[
              Css.borderBottomWidth(Css.px(0)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "modal-card-head",
        /* [] */0
      ]
    ]);

var checkIconStyles = Css.style(/* :: */[
      Css.marginLeft(Css.px(5)),
      /* [] */0
    ]);

var saveMessageStyles = Css.style(/* :: */[
      Css.color(Css.rgb(181, 128, 125)),
      /* :: */[
        Css.marginTop(Css.px(5)),
        /* [] */0
      ]
    ]);

var labelStyles = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.color(Css.rgb(181, 128, 125)),
            /* :: */[
              Css.textAlign(/* right */-379319332),
              /* [] */0
            ]
          ]),
      /* :: */[
        "column",
        /* [] */0
      ]
    ]);

var valueStyles = Css.merge(/* :: */[
      "column",
      /* :: */[
        "has-text-blac",
        /* [] */0
      ]
    ]);

export {
  modalHeaderStyles ,
  checkIconStyles ,
  saveMessageStyles ,
  labelStyles ,
  valueStyles ,
  
}
/* modalHeaderStyles Not a pure module */
